/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class algebra_msm_VariableBaseMSM */

#ifndef _Included_algebra_msm_VariableBaseMSM
#define _Included_algebra_msm_VariableBaseMSM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     algebra_msm_VariableBaseMSM
 * Method:    variableBaseSerialMSMNativeHelper
 * Signature: ([B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algebra_msm_VariableBaseMSM_variableBaseSerialMSMNativeHelper
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     algebra_msm_VariableBaseMSM
 * Method:    variableBaseDoubleMSMNativeHelper
 * Signature: (Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algebra_msm_VariableBaseMSM_variableBaseDoubleMSMNativeHelper
  (JNIEnv *, jclass, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
