/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class algebra_fft_FFTAuxiliary */

#ifndef _Included_algebra_fft_FFTAuxiliary
#define _Included_algebra_fft_FFTAuxiliary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     algebra_fft_FFTAuxiliary
 * Method:    serialRadix2FFTNativeHelper
 * Signature: (Ljava/util/List;[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algebra_fft_FFTAuxiliary_serialRadix2FFTNativeHelper
  (JNIEnv *, jclass, jobject, jbyteArray, jint);

/*
 * Class:     algebra_fft_FFTAuxiliary
 * Method:    serialRadix2FFTNativeBatchPartition
 * Signature: (Ljava/util/List;[BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algebra_fft_FFTAuxiliary_serialRadix2FFTNativeBatchPartition
  (JNIEnv *, jclass, jobject, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
