/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class algebra_msm_FixedBaseMSM */

#ifndef _Included_algebra_msm_FixedBaseMSM
#define _Included_algebra_msm_FixedBaseMSM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     algebra_msm_FixedBaseMSM
 * Method:    batchMSMNativeHelper
 * Signature: (IIIIII[B[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algebra_msm_FixedBaseMSM_batchMSMNativeHelper
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     algebra_msm_FixedBaseMSM
 * Method:    doubleBatchMSMNativeHelper
 * Signature: (IIIIIIIII[B[B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algebra_msm_FixedBaseMSM_doubleBatchMSMNativeHelper
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jbyteArray, jbyteArray, jbyteArray, jint);

/*
 * Class:     algebra_msm_FixedBaseMSM
 * Method:    fieldBatchMSMNativeHelper
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algebra_msm_FixedBaseMSM_fieldBatchMSMNativeHelper
  (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
