/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class algebra_msm_FixedBaseMSM */

#ifndef _Included_algebra_msm_FixedBaseMSM
#define _Included_algebra_msm_FixedBaseMSM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     algebra_msm_FixedBaseMSM
 * Method:    batchMSMNativeHelper
 * Signature: (IILjava/util/ArrayList;Ljava/util/ArrayList;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algebra_msm_FixedBaseMSM_batchMSMNativeHelper
  (JNIEnv *, jclass, jint, jint, jobject, jobject);

/*
 * Class:     algebra_msm_FixedBaseMSM
 * Method:    doubleBatchMSMNativeHelper
 * Signature: (IIIILjava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algebra_msm_FixedBaseMSM_doubleBatchMSMNativeHelper
  (JNIEnv *, jclass, jint, jint, jint, jint, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
