/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class algebra_fft_FFTAuxiliary */

#ifndef _Included_algebra_fft_FFTAuxiliary
#define _Included_algebra_fft_FFTAuxiliary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     algebra_fft_FFTAuxiliary
 * Method:    serialRadix2FFTNativeHelper
 * Signature: (Ljava/util/List;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algebra_fft_FFTAuxiliary_serialRadix2FFTNativeHelper
  (JNIEnv *, jclass, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
